name: bares_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.2.3

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.0.0
  http: ^1.2.0
  jwt_decode: ^0.3.1
  routefly: ^1.0.8
  signals: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
